### ISSUE TITLE
Test on SQL Server with GitHub Actions

### ISSUE THREAD

**Issue by theodorejb** [theodorejb/peachy-sql#13]
At one point this worked by simply adding the following workflow step:
```yml
- name: Install SQL Server
  uses: Particular/install-sql-server-action@v1.2.0
  with:
    connection-string-env-var: MSSQL_CONNECTION_STRING
    catalog: PeachySQL
```

But then it started causing this error:
> The term 'sqlcmd' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
